const seedSpots = [
  ['spot_1', 'Eiffel Tower', 'Iconic iron lattice tower in Paris.', 'Landmark', 'Paris', 'France', 48.8584, 2.2945, 'Champ de Mars, Paris', 0],
  ['spot_2', 'Colosseum', 'Ancient amphitheater in Rome.', 'Historical', 'Rome', 'Italy', 41.8902, 12.4922, 'Piazza del Colosseo, Rome', 0],
  ['spot_3', 'Rohtang Pass', 'High mountain pass near Manali with heavy snowfall.', 'Nature', 'Manali', 'India', 32.3726, 77.2375, 'Rohtang Pass, Himachal Pradesh', 1],
  ['spot_4', 'Solang Valley', 'Snow valley near Manali known for skiing.', 'Nature', 'Manali', 'India', 32.3195, 77.1518, 'Solang Valley, Himachal Pradesh', 1],
  ['spot_5', 'Athirappilly Falls', 'Largest waterfall in Kerala, India.', 'Nature', 'Thrissur', 'India', 10.2867, 76.5694, 'Athirappilly, Kerala', 0],
  ['spot_6', 'Dudhsagar Falls', 'Four-tiered waterfall on Goa-Karnataka border.', 'Nature', 'Goa', 'India', 15.3147, 74.3144, 'Dudhsagar, Goa', 1],
  ['spot_7', 'Taj Mahal', 'Ivory-white marble mausoleum in Agra.', 'Landmark', 'Agra', 'India', 27.1751, 78.0421, 'Dharmapuri, Agra', 0],
  ['spot_8', 'Spiti Valley', 'Cold desert mountain valley in Himachal Pradesh.', 'Nature', 'Spiti', 'India', 32.2432, 78.0358, 'Spiti Valley, Himachal Pradesh', 1],
  ['spot_9', 'Pangong Lake', 'High altitude lake in Ladakh.', 'Nature', 'Ladakh', 'India', 33.764, 78.6796, 'Pangong Tso, Ladakh', 1],
  ['spot_10', 'Niagara Falls', 'Large waterfalls on Canada-USA border.', 'Nature', 'Niagara Falls', 'Canada', 43.0962, -79.0377, 'Niagara Falls, Ontario', 0],
  ['spot_11', 'Mysore Palace', 'Magnificent royal palace and major tourist attraction in Mysore.', 'Landmark', 'Mysuru', 'India', 12.3052, 76.6552, 'Sayyaji Rao Rd, Mysuru, Karnataka', 0],
  ['spot_12', 'Coorg Coffee Estates', 'Lush green coffee plantations in the hills of Coorg.', 'Nature', 'Coorg', 'India', 12.3375, 75.8069, 'Madikeri, Coorg, Karnataka', 0],
  ['spot_13', 'Jog Falls', 'Second highest plunge waterfall in India.', 'Nature', 'Shimoga', 'India', 14.2269, 74.7921, 'Jog Falls, Shimoga, Karnataka', 0],
  ['spot_14', 'Netravati Peak', 'Stunning trekking peak in the Western Ghats of Karnataka.', 'Nature', 'Mangalore', 'India', 12.9762, 75.3998, 'Netravati Peak, Karnataka', 1],
  ['spot_15', 'Hampi', 'UNESCO World Heritage Site with ancient Vijayanagara ruins.', 'Historical', 'Hampi', 'India', 15.335, 76.46, 'Hampi, Ballari District, Karnataka', 0],
  ['spot_16', 'Badami Caves', 'Ancient rock-cut cave temples carved in 6th century.', 'Historical', 'Badami', 'India', 15.9149, 75.676, 'Badami, Bagalkot, Karnataka', 0],
  ['spot_17', 'Shivanasamudra Falls', 'Twin waterfalls on the Kaveri river in Karnataka.', 'Nature', 'Mandya', 'India', 12.27, 77.16, 'Shivanasamudra, Mandya, Karnataka', 0],
  ['spot_18', 'Varkala Beach', 'Stunning cliffside beach with mineral springs in Kerala.', 'Beach', 'Varkala', 'India', 8.7379, 76.7163, 'Varkala, Thiruvananthapuram, Kerala', 0],
  ['spot_19', 'Kovalam Beach', 'Famous crescent shaped beach near Thiruvananthapuram.', 'Beach', 'Kovalam', 'India', 8.4004, 76.9787, 'Kovalam, Thiruvananthapuram, Kerala', 0],
  ['spot_20', 'Munnar Tea Gardens', 'Rolling hills covered with lush green tea plantations.', 'Nature', 'Munnar', 'India', 10.0889, 77.0595, 'Munnar, Idukki, Kerala', 0],
  ['spot_21', 'Alleppey Backwaters', 'Venice of the East - famous houseboat rides through backwaters.', 'Nature', 'Alappuzha', 'India', 9.4981, 76.3388, 'Alappuzha, Kerala', 0],
  ['spot_22', 'Wayanad Wildlife Sanctuary', 'Dense forest sanctuary home to elephants and tigers.', 'Nature', 'Wayanad', 'India', 11.6854, 76.132, 'Wayanad, Kerala', 1],
  ['spot_23', 'Calangute Beach', 'Queen of beaches in North Goa, popular tourist destination.', 'Beach', 'Goa', 'India', 15.544, 73.7528, 'Calangute, North Goa', 0],
  ['spot_24', 'Palolem Beach', 'Crescent shaped peaceful beach in South Goa.', 'Beach', 'Goa', 'India', 15.01, 74.0232, 'Palolem, South Goa', 0],
  ['spot_25', 'Baga Beach', 'Famous beach known for nightlife and water sports.', 'Beach', 'Goa', 'India', 15.5569, 73.752, 'Baga, North Goa', 0],
  ['spot_26', 'Dudhsagar Beach', 'Remote beach accessible only by boat in South Goa.', 'Beach', 'Goa', 'India', 15.3147, 74.0134, 'Canacona, South Goa', 1],
  ['spot_27', 'Charminar', 'Iconic 16th century mosque and monument in Hyderabad.', 'Historical', 'Hyderabad', 'India', 17.3616, 78.4747, 'Charminar, Hyderabad, Telangana', 0],
  ['spot_28', 'Golconda Fort', 'Magnificent medieval fort and former diamond trading centre.', 'Historical', 'Hyderabad', 'India', 17.3833, 78.4011, 'Golconda, Hyderabad, Telangana', 0],
  ['spot_29', 'Araku Valley', 'Scenic valley with coffee plantations and tribal culture.', 'Nature', 'Visakhapatnam', 'India', 18.3273, 82.8757, 'Araku Valley, Andhra Pradesh', 1],
  ['spot_30', 'Hawa Mahal', 'Palace of Winds - iconic pink sandstone palace in Jaipur.', 'Landmark', 'Jaipur', 'India', 26.9239, 75.8267, 'Hawa Mahal Rd, Jaipur, Rajasthan', 0],
  ['spot_31', 'Jaisalmer Fort', 'Living fort rising from the Thar Desert in golden sandstone.', 'Historical', 'Jaisalmer', 'India', 26.9157, 70.9083, 'Jaisalmer, Rajasthan', 0],
  ['spot_32', 'Pushkar Lake', 'Sacred lake surrounded by 52 ghats and Hindu temples.', 'Historical', 'Pushkar', 'India', 26.4897, 74.5511, 'Pushkar, Ajmer, Rajasthan', 0],
  ['spot_33', 'Kedarnath Temple', 'Ancient Hindu temple in the Himalayas at 3583m altitude.', 'Temple', 'Rudraprayag', 'India', 30.7346, 79.0669, 'Kedarnath, Uttarakhand', 1],
  ['spot_34', 'Valley of Flowers', 'UNESCO World Heritage alpine valley with stunning wildflowers.', 'Nature', 'Chamoli', 'India', 30.7283, 79.605, 'Valley of Flowers, Uttarakhand', 1],
  ['spot_35', 'Nainital Lake', 'Beautiful pear shaped lake surrounded by hills in Uttarakhand.', 'Nature', 'Nainital', 'India', 29.3919, 79.4542, 'Nainital, Uttarakhand', 0],
  ['spot_36', 'Sanjeevini Circle Test Spot', 'Test location for photo validation - Lokanayakanagar, Mysore.', 'General', 'Mysuru', 'India', 12.350731, 76.627249, '9th Cross, Lokanayakanagar, Sanjeevini Circle, Mysuru 570016', 0],
  ['spot_37', 'India Gate', 'War memorial arch and one of the most iconic landmarks of Delhi.', 'Landmark', 'New Delhi', 'India', 28.6129, 77.2295, 'Rajpath, New Delhi', 0],
  ['spot_38', 'Gateway of India', 'Historic waterfront arch overlooking the Arabian Sea in Mumbai.', 'Landmark', 'Mumbai', 'India', 18.922, 72.8347, 'Apollo Bandar, Mumbai', 0],
  ['spot_39', 'Qutub Minar', 'UNESCO-listed minaret and monument complex in Delhi.', 'Historical', 'New Delhi', 'India', 28.5244, 77.1855, 'Mehrauli, New Delhi', 0],
  ['spot_40', 'Red Fort', 'Iconic Mughal fort complex in Old Delhi.', 'Historical', 'Delhi', 'India', 28.6562, 77.241, 'Netaji Subhash Marg, Delhi', 0],
  ['spot_41', 'Agra Fort', 'Massive red sandstone fort and UNESCO World Heritage site in Agra.', 'Historical', 'Agra', 'India', 27.1795, 78.0211, 'Rakabganj, Agra', 0],
  ['spot_42', 'Amer Fort', 'Hilltop Rajput fort overlooking Maota Lake in Jaipur.', 'Historical', 'Jaipur', 'India', 26.9855, 75.8513, 'Devisinghpura, Amer, Jaipur', 0],
  ['spot_43', 'Mehrangarh Fort', 'Vast fort complex towering above the blue city of Jodhpur.', 'Historical', 'Jodhpur', 'India', 26.2978, 73.0181, 'Fort Rd, Jodhpur', 0],
  ['spot_44', 'City Palace Udaipur', 'Lake-facing palace complex in Udaipur.', 'Landmark', 'Udaipur', 'India', 24.5767, 73.6835, 'Old City, Udaipur', 0],
  ['spot_45', 'Golden Temple', 'Most revered Sikh gurdwara set around a sacred pool.', 'Temple', 'Amritsar', 'India', 31.62, 74.8765, 'Golden Temple Rd, Amritsar', 0],
  ['spot_46', 'Vaishno Devi', 'Major Hindu pilgrimage temple nestled in the Trikuta hills.', 'Temple', 'Katra', 'India', 33.0307, 74.9497, 'Katra, Jammu and Kashmir', 1],
  ['spot_47', 'Badrinath Temple', 'Sacred Himalayan temple dedicated to Lord Vishnu.', 'Temple', 'Chamoli', 'India', 30.7433, 79.4938, 'Badrinath, Uttarakhand', 1],
  ['spot_48', 'Meenakshi Amman Temple', 'Grand Dravidian temple famed for its gopurams.', 'Temple', 'Madurai', 'India', 9.9195, 78.1193, 'Madurai Main, Tamil Nadu', 0],
  ['spot_49', 'Brihadeeswara Temple', 'UNESCO-listed Chola temple in Thanjavur.', 'Temple', 'Thanjavur', 'India', 10.7828, 79.1318, 'Membalam Rd, Thanjavur', 0],
  ['spot_50', 'Ramanathaswamy Temple', 'Historic temple on Rameswaram island known for long corridors.', 'Temple', 'Rameswaram', 'India', 9.2881, 79.3174, 'Rameswaram, Tamil Nadu', 0],
  ['spot_51', 'Jagannath Temple', 'One of the Char Dham pilgrimage temples in Puri.', 'Temple', 'Puri', 'India', 19.8049, 85.8186, 'Puri, Odisha', 0],
  ['spot_52', 'Konark Sun Temple', '13th-century chariot-shaped temple in Odisha.', 'Historical', 'Konark', 'India', 19.8876, 86.0945, 'Konark, Odisha', 0],
  ['spot_53', 'Mahabodhi Temple', 'UNESCO-listed Buddhist temple marking the enlightenment of Buddha.', 'Temple', 'Bodh Gaya', 'India', 24.6959, 84.9911, 'Bodh Gaya, Bihar', 0],
  ['spot_54', 'Ajanta Caves', 'Ancient Buddhist cave monuments with exquisite murals.', 'Historical', 'Aurangabad', 'India', 20.5519, 75.7033, 'Ajanta, Maharashtra', 0],
  ['spot_55', 'Ellora Caves', 'Rock-cut cave complex featuring Hindu, Buddhist and Jain monuments.', 'Historical', 'Aurangabad', 'India', 20.0258, 75.179, 'Ellora, Maharashtra', 0],
  ['spot_56', 'Sanchi Stupa', 'Ancient Buddhist stupa complex in Madhya Pradesh.', 'Historical', 'Sanchi', 'India', 23.4794, 77.7397, 'Sanchi, Madhya Pradesh', 0],
  ['spot_57', 'Khajuraho Temples', 'UNESCO temple group famed for intricate stone carvings.', 'Historical', 'Khajuraho', 'India', 24.8518, 79.9199, 'Khajuraho, Madhya Pradesh', 0],
  ['spot_58', 'Victoria Memorial', 'Grand marble memorial and museum in Kolkata.', 'Landmark', 'Kolkata', 'India', 22.5448, 88.3426, 'Queens Way, Kolkata', 0],
  ['spot_59', 'Howrah Bridge', 'Cantilever bridge and enduring symbol of Kolkata.', 'Landmark', 'Kolkata', 'India', 22.585, 88.3468, 'Howrah, West Bengal', 0],
  ['spot_60', 'Marine Drive', 'Iconic seafront promenade in Mumbai.', 'General', 'Mumbai', 'India', 18.943, 72.8238, 'Marine Drive, Mumbai', 0],
  ['spot_61', 'Marina Beach', 'One of the longest urban beaches in the world.', 'Beach', 'Chennai', 'India', 13.0499, 80.2824, 'Marina Beach, Chennai', 0],
  ['spot_62', 'Radhanagar Beach', 'White-sand beach in the Andaman Islands.', 'Beach', 'Swaraj Dweep', 'India', 11.9845, 92.9497, 'Havelock Island, Andaman and Nicobar', 1],
  ['spot_63', 'Cellular Jail', 'Historic colonial prison and national memorial in Port Blair.', 'Historical', 'Port Blair', 'India', 11.6738, 92.7626, 'Port Blair, Andaman and Nicobar', 0],
  ['spot_64', 'Kaziranga National Park', 'World-famous wildlife reserve known for the one-horned rhino.', 'Nature', 'Kaziranga', 'India', 26.5775, 93.1711, 'Kaziranga, Assam', 1],
  ['spot_65', 'Sundarbans National Park', 'Mangrove wilderness and tiger reserve in Bengal delta.', 'Nature', 'Sundarbans', 'India', 21.9497, 88.8776, 'Sundarbans, West Bengal', 1],
  ['spot_66', 'Gir National Park', 'Last natural habitat of the Asiatic lion.', 'Nature', 'Junagadh', 'India', 21.124, 70.8247, 'Gir, Gujarat', 1],
  ['spot_67', 'Rann of Kutch', 'Vast salt desert famed for its white landscapes.', 'Nature', 'Kutch', 'India', 23.7337, 69.8597, 'Great Rann of Kutch, Gujarat', 1],
  ['spot_68', 'Statue of Unity', 'Worlds tallest statue overlooking the Narmada river.', 'Landmark', 'Kevadia', 'India', 21.838, 73.7191, 'Kevadia, Gujarat', 0],
  ['spot_69', 'Dal Lake', 'Scenic lake in Srinagar known for shikaras and houseboats.', 'Nature', 'Srinagar', 'India', 34.1204, 74.8474, 'Dal Lake, Srinagar', 0],
  ['spot_70', 'Leh Palace', 'Historic royal palace overlooking Leh town.', 'Historical', 'Leh', 'India', 34.1673, 77.5848, 'Leh, Ladakh', 0],
  ['spot_71', 'Nubra Valley', 'High-altitude cold desert valley with dunes and monasteries.', 'Nature', 'Leh', 'India', 34.6257, 77.5515, 'Nubra Valley, Ladakh', 1],
  ['spot_72', 'Tsomgo Lake', 'Glacial lake near Gangtok high in the eastern Himalayas.', 'Nature', 'Gangtok', 'India', 27.3774, 88.7618, 'Tsomgo Lake, Sikkim', 1],
  ['spot_73', 'Darjeeling Himalayan Railway', 'Mountain railway route through the tea hills of Darjeeling.', 'Historical', 'Darjeeling', 'India', 27.041, 88.2663, 'Darjeeling, West Bengal', 0],
  ['spot_74', 'Cherrapunji', 'Rain-soaked hill region with caves and waterfalls.', 'Nature', 'Sohra', 'India', 25.2702, 91.7326, 'Cherrapunji, Meghalaya', 1],
  ['spot_75', 'Living Root Bridge', 'Handwoven root bridge in the forests of Meghalaya.', 'Nature', 'Nongriat', 'India', 25.2472, 91.7112, 'Nongriat, Meghalaya', 1],
  ['spot_76', 'Tawang Monastery', 'Largest monastery in India set in Arunachal mountains.', 'Temple', 'Tawang', 'India', 27.5865, 91.8594, 'Tawang, Arunachal Pradesh', 1],
  ['spot_77', 'Loktak Lake', 'Large freshwater lake known for floating phumdis.', 'Nature', 'Bishnupur', 'India', 24.4971, 93.7982, 'Loktak Lake, Manipur', 1],
  ['spot_78', 'Dzukou Valley', 'High-altitude valley on the Nagaland-Manipur border.', 'Nature', 'Kohima', 'India', 25.5588, 94.091, 'Dzukou Valley', 1],
  ['spot_79', 'Rishikesh', 'Yoga capital and riverfront adventure destination.', 'General', 'Rishikesh', 'India', 30.0869, 78.2676, 'Rishikesh, Uttarakhand', 0],
  ['spot_80', 'Auli', 'Popular skiing destination with panoramic Himalayan views.', 'Nature', 'Joshimath', 'India', 30.5284, 79.5641, 'Auli, Uttarakhand', 1],
  ['spot_81', 'Mahabalipuram Shore Temple', 'Seaside Pallava temple complex on the Bay of Bengal.', 'Temple', 'Mahabalipuram', 'India', 12.6166, 80.1999, 'Mahabalipuram, Tamil Nadu', 0],
  ['spot_82', 'Kanyakumari Beach', 'Southern tip beach where three seas meet.', 'Beach', 'Kanyakumari', 'India', 8.078, 77.5411, 'Kanyakumari, Tamil Nadu', 0],
  ['spot_83', 'Arambol Beach', 'Relaxed North Goa beach with cliffs and sunset views.', 'Beach', 'Goa', 'India', 15.6868, 73.7047, 'Arambol, North Goa', 0],
  ['spot_84', 'Mahabaleshwar', 'Hill station known for viewpoints and strawberry farms.', 'Nature', 'Mahabaleshwar', 'India', 17.9237, 73.6586, 'Mahabaleshwar, Maharashtra', 0],
  ['spot_85', 'Lonavala', 'Hill getaway with caves, forts and monsoon scenery.', 'Nature', 'Lonavala', 'India', 18.7546, 73.4062, 'Lonavala, Maharashtra', 0],
  ['spot_86', 'Chitrakote Falls', 'Broad horseshoe waterfall in Bastar often called the Niagara of India.', 'Nature', 'Jagdalpur', 'India', 19.2077, 81.6961, 'Chitrakote, Chhattisgarh', 0],
];

module.exports = { seedSpots };
